In [1]:
import numpy as np

In [29]:
# Problem 1: array creation

# 1 
a = np.arange(10)

# 2
b = np.ones((3,3))

# 3
c = np.arange(16).reshape(4,4)

print('a:\n',a,'\n\nb:\n', b,'\n\nc:\n', c)

a:
 [0 1 2 3 4 5 6 7 8 9] 

b:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

c:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [49]:
# Problem 2: Array operations

# 4 
d = np.random.rand(25).reshape(5,5)
print(d)
print(np.max(d))
print(np.min(d))

[[0.87098368 0.4904903  0.17394611 0.65189301 0.87729069]
 [0.80210654 0.6616362  0.27009807 0.57864583 0.69151454]
 [0.2768997  0.12855945 0.71096067 0.86063749 0.11259324]
 [0.39362126 0.30069494 0.79628491 0.59001982 0.83057215]
 [0.20114097 0.96457786 0.83599594 0.78704676 0.47694642]]
0.9645778648511596
0.11259323991665615


In [55]:
# 5

e = np.random.rand(10)
print(e)
print(np.mean(e))
print(np.std(e))

[0.64555037 0.01616257 0.75220925 0.70397261 0.78889401 0.33136013
 0.6524314  0.44407549 0.63059743 0.44339021]
0.5408643475512401
0.22412526465195756


In [177]:
# 6
f = np.arange(4).reshape(2,2)
print(f)

g = np.eye(2)
print(g)

dot_prod = np.dot(f, g)
print(dot_prod)

[[0 1]
 [2 3]]
[[1. 0.]
 [0. 1.]]
[[0. 1.]
 [2. 3.]]


In [65]:
# Problem 3: Indexing and slicing

# 7 
h = np.arange(10,20)
print(h)
print(h[3:9])

[10 11 12 13 14 15 16 17 18 19]
[13 14 15 16 17 18]


In [71]:
# 8 
i = np.arange(1,10).reshape(3,3)
print(i)
print(i[0,1],i[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2 9


In [97]:
# Problem 4: Array manipulation
# 9
k = np.random.rand(12).reshape(3,4)
print(k)

[[0.84711802 0.44398078 0.34542053 0.38598417]
 [0.76345068 0.9231784  0.23185621 0.04351087]
 [0.02850702 0.19314868 0.93705827 0.68516343]]


In [111]:
# 10
l = np.random.randint(1,10,16).reshape(4,4)
print(l)
print(l.reshape(16))

[[6 9 6 2]
 [4 9 3 6]
 [8 2 8 1]
 [3 1 7 3]]
[6 9 6 2 4 9 3 6 8 2 8 1 3 1 7 3]


In [181]:
# Problem 5: Mathematical functions
# 11
j = np.random.rand(10)
print(j)
print(np.exp(j))

[0.40084769 0.3274614  0.10254593 0.33355361 0.4551986  0.15110246
 0.45017503 0.41141286 0.37285318 0.3844311 ]
[1.49308984 1.3874415  1.10798819 1.39591987 1.57648645 1.16311582
 1.56858671 1.50894822 1.45187117 1.46877849]
[0.69319465 0.69379897 0.79172382 0.69334626 0.69889758 0.75159851
 0.69816964 0.69391928 0.6922238  0.69245463]


In [137]:
# 12
m = np.random.randint(1,100,5)
n = np.random.randint(1,100,5)

print(m)
print(n)
print("sum: ", m + n)
print("diff: ", m - n)
print("product: ", m * n)
print("div: ", m / n)


[44 94  7 96 67]
[26 80 23 78 20]
sum:  [ 70 174  30 174  87]
diff:  [ 18  14 -16  18  47]
product:  [1144 7520  161 7488 1340]
div:  [1.69230769 1.175      0.30434783 1.23076923 3.35      ]


In [147]:
# Problem 6: Statistical operations

# 13
o = np.random.randint(1,100,25).reshape(5,5)
print(o)
print(np.mean(o, axis=0))
print(np.mean(o, axis=1))

[[27 63  4 15 49]
 [69 52  5 80 88]
 [67 99  3 19 36]
 [41 93 18 72 60]
 [92  2 40 12 60]]
[59.2 61.8 14.  39.6 58.6]
[31.6 58.8 44.8 56.8 41.2]


In [149]:
# 14

p = np.random.randint(1,100,10)
print(p)
print(np.sort(p))

[68 91 71 71 28 79 65 52 76  4]
[ 4 28 52 65 68 71 71 76 79 91]


In [161]:
# Problem 7: Broadcasting

# 15
q = np.arange(1,10).reshape(3,3)
print(q)

r = np.array([1,1,1])
s = (q + r)
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [187]:
# Problem 8: Boolean indexing

# 16
t = np.random.rand(10)
print(t)
x = (t > 0.5)
print(x)
u = np.where(t > 0.5, 1, 0)
print(u)


[0.26243766 0.42629868 0.61628726 0.39674483 0.82114177 0.58152502
 0.81908061 0.38973746 0.42657848 0.07238842]
[False False  True False  True  True  True False False False]
[0 0 1 0 1 1 1 0 0 0]


In [203]:
# Problem 9: set operations

arr1 = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)
print(arr1)
print(arr2)

uni = np.union1d(arr1, arr2)
print(uni)

intsec = np.intersect1d(arr1, arr2)
print(intsec)

[8 7 9 2 2]
[3 4 9 4 6]
[2 3 4 6 7 8 9]
[9]


In [207]:
# Problem 10
# Create a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Compute the determinant
determinant = np.linalg.det(matrix)

# Compute the inverse
inverse = np.linalg.inv(matrix)

# Display the matrix, determinant, and inverse
print("Matrix:\n", matrix)
print("Determinant:", determinant)
print("Inverse:\n", inverse)

Matrix:
 [[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# Problem 11
# 1 
a = np.arange(0,16).reshape(4,4)
b = np.mean(a, axis=1)

c = a - b

print(a,"\n")
print(b,"\n")
print(c,"\n")


# Problem 12: Array Broadcasting
d = np.arange(0,9).reshape(3,3)
e = np.array([1,2,3])
f = d * e

print(d,"\n")
print(e,"\n")
print(f,"\n")

# Problem 13: Advanced indexing
mat1 = np.random.rand(25).reshape(5,5)
print(mat1)

mat2 = mat1[mat1 > 0.5] * -1
print(mat2)

# Problem 14: Fancy Indexing
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr1[[1,3,5,7]] = -1
print(arr1)

# Problem 15: Matrix multiplication
arr3 = np.arange(0,9).reshape(3,3)
arr4 = np.arange(10,19).reshape(3,3)
arr5 = arr3 * arr4
print(arr3,"\n")
print(arr4,"\n")
print(arr5,"\n")

In [333]:
# Problem 11
# 1 
a = np.arange(0,16).reshape(4,4)
b = np.mean(a, axis=1)

c = a - b

print(a,"\n")
print(b,"\n")
print(c,"\n")


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 1.5  5.5  9.5 13.5] 

[[ -1.5  -4.5  -7.5 -10.5]
 [  2.5  -0.5  -3.5  -6.5]
 [  6.5   3.5   0.5  -2.5]
 [ 10.5   7.5   4.5   1.5]] 



In [327]:
a = np.arange(0, 16).reshape(4, 4)
row_means = a.mean(axis=1, keepdims=True)
c = a - row_means

print(a, "\n")
print(row_means, "\n")
print(c, "\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 1.5]
 [ 5.5]
 [ 9.5]
 [13.5]] 

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]] 



In [345]:
# Problem 13: Advanced indexing
mat1 = np.random.rand(25).reshape(5,5)
print(mat1)

mat1[mat1 > 0.5] *= -1
print(mat1)

[[0.63620215 0.51371147 0.83840768 0.88637378 0.52009264]
 [0.98346314 0.2151481  0.65403632 0.37967299 0.09290071]
 [0.94362738 0.03097087 0.25659916 0.57447213 0.91269506]
 [0.68689319 0.52548616 0.37087289 0.39671863 0.24736463]
 [0.88145048 0.2525031  0.38602004 0.17957702 0.94564653]]
[[-0.63620215 -0.51371147 -0.83840768 -0.88637378 -0.52009264]
 [-0.98346314  0.2151481  -0.65403632  0.37967299  0.09290071]
 [-0.94362738  0.03097087  0.25659916 -0.57447213 -0.91269506]
 [-0.68689319 -0.52548616  0.37087289  0.39671863  0.24736463]
 [-0.88145048  0.2525031   0.38602004  0.17957702 -0.94564653]]


In [347]:
mat2 = np.random.randint(0,100,25).reshape(5,5)
print(mat2)

mat2[mat2 > 80] = 0
print(mat2)

[[70  9 44  7 14]
 [ 6 10 89 25 66]
 [81 65 41 29 36]
 [24 64 15 51 58]
 [74 66 98 32 70]]
[[70  9 44  7 14]
 [ 6 10  0 25 66]
 [ 0 65 41 29 36]
 [24 64 15 51 58]
 [74 66  0 32 70]]


In [349]:
# Problem 15: Matrix multiplication
arr3 = np.arange(0,9).reshape(3,3)
arr4 = np.arange(10,19).reshape(3,3)
arr5 = arr3 * arr4
print(arr3,"\n")
print(arr4,"\n")
print(arr5,"\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[10 11 12]
 [13 14 15]
 [16 17 18]] 

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]] 



In [351]:
# Problem 15: Matrix multiplication
arr3 = np.arange(0,9).reshape(3,3)
arr4 = np.arange(10,19).reshape(3,3)
arr5 = np.dot(arr3, arr4)
print(arr3,"\n")
print(arr4,"\n")
print(arr5,"\n")

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[10 11 12]
 [13 14 15]
 [16 17 18]] 

[[ 45  48  51]
 [162 174 186]
 [279 300 321]] 

