In [1]:
my_list = [1, [1,2,3], 4]
max(my_list)

TypeError: '>' not supported between instances of 'list' and 'int'

In [7]:
import numpy as np

x = np.arange(9).reshape(3,3)

In [9]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
x[[0]] = x[[1]]

In [13]:
print(x)

[[3 4 5]
 [3 4 5]
 [6 7 8]]


In [53]:
x = np.arange(9).reshape(3,3)

In [55]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [65]:
x[[0,0,1,1],[0,1,0,1]].reshape(2,2)

array([[0, 1],
       [3, 4]])

In [67]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [91]:
np.linspace(0,1,11, endpoint=True)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])